# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
#     - name: Checkout
#       uses: actions/checkout@v1

    - name: Run API Tests
      id: run-newman
      run: |
        npm install -g newman-reporter-htmlextra
        newman run testgoogle.postman_collection.json -r cli,htmlextra
    
    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
